<?php

namespace Sce\UserBundle\Repository;

/**
 * CarteJenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteJenRepository extends \Doctrine\ORM\EntityRepository
{
}
