<?php

namespace Sce\UserBundle\Repository;

/**
 * CategorieCarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCarteRepository extends \Doctrine\ORM\EntityRepository
{
}
