<?php

namespace Sce\UserBundle\Repository;

/**
 * JenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JenRepository extends \Doctrine\ORM\EntityRepository
{
}
