discipline_index:
    path:     /
    defaults: { _controller: "UserBundle:Discipline:index" }
    methods:  GET

discipline_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:Discipline:show" }
    methods:  GET

discipline_new:
    path:     /new
    defaults: { _controller: "UserBundle:Discipline:new" }
    methods:  [GET, POST]

discipline_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:Discipline:edit" }
    methods:  [GET, POST]

discipline_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:Discipline:delete" }
    methods:  DELETE
